package analysis;

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.TimeUnit;
import rsid.GlobalConfig;

/**
 * Generates a Snakemake workflow wrapping the existing per-locus pipeline (PLINK subset -> LD),
 * for optional remote execution on an HPC cluster over the user's own SSH access. See
 * GlobalConfig.HpcConfig for the opt-in configuration this reads.
 *
 * IMPORTANT: as of this class's introduction, nothing in the running application actually calls
 * submit()/pollStatus() from the UI yet — Resources & Settings can only save/validate HpcConfig.
 * Wiring an actual "run on cluster" action into the project pipeline is future work (see
 * DECISIONS.md). This class was also never exercised against a real SSH host while it was
 * written: only the pure logic (Snakefile content, poll-interval selection, remote path
 * validation) is unit-tested; submit()/pollStatus() themselves are untested against a live target.
 *
 * All remote command construction uses ProcessBuilder argument-array form, never a concatenated
 * shell string, and remote-facing user input (remoteWorkDir, sshHost, sshUser) is validated
 * against shell metacharacters first.
 */
public class SnakemakeSubmitter {

    /** Characters that must never appear in a value that ends up as part of a remote command,
     *  even though ProcessBuilder's argument-array form already prevents local shell injection —
     *  the *remote* shell (bash on the cluster) still interprets whatever string we send it as
     *  the ssh command's argument, so this is a second, independent line of defense. */
    private static final String DANGEROUS_CHARS = ";&|`$(){}<>\n\r";

    public static class ValidationException extends Exception {
        public ValidationException(String message) { super(message); }
    }

    /** Throws if value contains a shell metacharacter that could change what the remote command
     *  does. Called on every user-supplied config value before it's used in a remote command. */
    public static void validateNoShellMetachars(String fieldName, String value) throws ValidationException {
        if (value == null) return;
        for (char c : DANGEROUS_CHARS.toCharArray()) {
            if (value.indexOf(c) >= 0) {
                throw new ValidationException(fieldName + " contains a disallowed character ('" + c +
                    "') that could be interpreted by the remote shell: " + value);
            }
        }
    }

    /** Generates Snakefile content for the given loci, with a `module load` prefix per
     *  moduleNames entry ahead of each rule's shell command. Pure string generation, no I/O. */
    public static String generateSnakefile(List<Integer> lociIndices, String refPanelPath,
                                            String plinkSubsetsDir, String ldResultsDir,
                                            Map<String, String> moduleNames) {
        String plinkModule = moduleLoadLine(moduleNames, "plink");
        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by SnakemakeSubmitter — do not edit by hand.\n");
        sb.append("LOCI = [").append(joinInts(lociIndices)).append("]\n\n");

        sb.append("rule all:\n");
        sb.append("    input:\n");
        sb.append("        expand(\"").append(ldResultsDir).append("/locus_{locus}_pairwise.ld\", locus=LOCI)\n\n");

        sb.append("rule subset_locus:\n");
        sb.append("    output:\n");
        sb.append("        \"").append(plinkSubsetsDir).append("/locus_{locus}.bed\"\n");
        sb.append("    threads: 1\n");
        sb.append("    shell:\n");
        sb.append("        \"\"\"\n");
        if (!plinkModule.isEmpty()) sb.append("        ").append(plinkModule).append("\n");
        sb.append("        plink --bfile ").append(refPanelPath)
          .append(" --chr $(cat loci/{wildcards.locus}.chr)")
          .append(" --from-bp $(cat loci/{wildcards.locus}.from)")
          .append(" --to-bp $(cat loci/{wildcards.locus}.to)")
          .append(" --make-bed --allow-extra-chr")
          .append(" --out ").append(plinkSubsetsDir).append("/locus_{wildcards.locus} --silent\n");
        sb.append("        \"\"\"\n\n");

        sb.append("rule ld_locus:\n");
        sb.append("    input:\n");
        sb.append("        \"").append(plinkSubsetsDir).append("/locus_{locus}.bed\"\n");
        sb.append("    output:\n");
        sb.append("        \"").append(ldResultsDir).append("/locus_{locus}_pairwise.ld\"\n");
        sb.append("    threads: 1\n");
        sb.append("    shell:\n");
        sb.append("        \"\"\"\n");
        if (!plinkModule.isEmpty()) sb.append("        ").append(plinkModule).append("\n");
        sb.append("        plink --bfile ").append(plinkSubsetsDir).append("/locus_{wildcards.locus}")
          .append(" --r2 square --allow-extra-chr")
          .append(" --out ").append(ldResultsDir).append("/locus_{wildcards.locus}_pairwise --silent\n");
        sb.append("        \"\"\"\n");

        return sb.toString();
    }

    private static String moduleLoadLine(Map<String, String> moduleNames, String tool) {
        if (moduleNames == null) return "";
        String mod = moduleNames.get(tool);
        return (mod == null || mod.isEmpty()) ? "" : "module load " + mod;
    }

    private static String joinInts(List<Integer> ints) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < ints.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(ints.get(i));
        }
        return sb.toString();
    }

    /** Picks a poll interval within [hpc.pollIntervalMinMinutes, hpc.pollIntervalMaxMinutes] based
     *  on a rough job-size heuristic: more loci = a longer expected run = a longer poll interval,
     *  so a small job gets checked frequently and a huge one doesn't get hammered with pointless
     *  polls. Deliberately simple (linear ramp, capped at 200 loci) rather than trying to model
     *  actual per-locus runtime, which varies too much by locus size to estimate reliably here. */
    public static int pickPollIntervalMinutes(GlobalConfig.HpcConfig hpc, int totalLoci) {
        int lo = Math.max(1, hpc.pollIntervalMinMinutes);
        int hi = Math.max(lo, hpc.pollIntervalMaxMinutes);
        if (totalLoci <= 0) return lo;
        double fraction = Math.min(1.0, totalLoci / 200.0);
        return (int) Math.round(lo + fraction * (hi - lo));
    }

    /** Builds the argument array for copying a file to the remote host — never a shell string. */
    public static List<String> scpCommand(GlobalConfig.HpcConfig hpc, String localPath, String remotePath)
            throws ValidationException {
        validateNoShellMetachars("remoteWorkDir", hpc.remoteWorkDir);
        validateNoShellMetachars("sshHost", hpc.sshHost);
        validateNoShellMetachars("sshUser", hpc.sshUser);
        List<String> cmd = new ArrayList<>();
        cmd.add("scp");
        if (!hpc.sshKeyPath.isEmpty()) { cmd.add("-i"); cmd.add(hpc.sshKeyPath); }
        cmd.add(localPath);
        cmd.add(hpc.sshUser + "@" + hpc.sshHost + ":" + remotePath);
        return cmd;
    }

    /** Builds the argument array for running a fixed remote wrapper script over ssh — prefer this
     *  shape (a single fixed script name) over interpolating a long inline remote command string,
     *  per the class-level safety note. */
    public static List<String> sshRunScriptCommand(GlobalConfig.HpcConfig hpc, String remoteScriptPath)
            throws ValidationException {
        validateNoShellMetachars("remoteWorkDir", hpc.remoteWorkDir);
        validateNoShellMetachars("sshHost", hpc.sshHost);
        validateNoShellMetachars("sshUser", hpc.sshUser);
        validateNoShellMetachars("remoteScriptPath", remoteScriptPath);
        List<String> cmd = new ArrayList<>();
        cmd.add("ssh");
        if (!hpc.sshKeyPath.isEmpty()) { cmd.add("-i"); cmd.add(hpc.sshKeyPath); }
        cmd.add(hpc.sshUser + "@" + hpc.sshHost);
        cmd.add("bash");
        cmd.add(remoteScriptPath);
        return cmd;
    }

    /** Content for the fixed remote wrapper script scp'd over and then run via
     *  sshRunScriptCommand() — this is the ONLY thing actually executed on the remote host,
     *  so its content is fully determined here (not built from free-form interpolation at
     *  ssh-invocation time). */
    public static String generateRemoteWrapperScript(GlobalConfig.HpcConfig hpc, int cores, int jobs)
            throws ValidationException {
        validateNoShellMetachars("remoteWorkDir", hpc.remoteWorkDir);
        StringBuilder sb = new StringBuilder();
        sb.append("#!/bin/bash\n");
        sb.append("set -e\n");
        sb.append("cd ").append(hpc.remoteWorkDir).append("\n");
        sb.append("snakemake --cores ").append(Math.max(1, cores))
          .append(" --jobs ").append(Math.max(1, jobs)).append("\n");
        return sb.toString();
    }

    /** Tries `squeue -u <user>` first, falls back to `qstat -u <user>` if that fails — loosely
     *  parses whatever comes back (job lines present = running). Not tested against a live
     *  scheduler; kept intentionally simple since exact output format varies by cluster/scheduler
     *  version in ways this class has had no real target to verify against. */
    public static boolean pollStatus(GlobalConfig.HpcConfig hpc) throws IOException, InterruptedException, ValidationException {
        validateNoShellMetachars("sshHost", hpc.sshHost);
        validateNoShellMetachars("sshUser", hpc.sshUser);
        String output = runRemoteStatusCommand(hpc, "squeue", "-u", hpc.sshUser);
        if (output == null) output = runRemoteStatusCommand(hpc, "qstat", "-u", hpc.sshUser);
        if (output == null) return false; // neither scheduler command worked — treat as "not running"
        // Header line only (or empty) means no jobs; more than one non-empty line means jobs present.
        String[] lines = output.split("\n");
        int nonEmpty = 0;
        for (String l : lines) if (!l.trim().isEmpty()) nonEmpty++;
        return nonEmpty > 1;
    }

    private static String runRemoteStatusCommand(GlobalConfig.HpcConfig hpc, String... remoteCmd)
            throws ValidationException {
        List<String> cmd = new ArrayList<>();
        cmd.add("ssh");
        if (!hpc.sshKeyPath.isEmpty()) { cmd.add("-i"); cmd.add(hpc.sshKeyPath); }
        cmd.add(hpc.sshUser + "@" + hpc.sshHost);
        cmd.addAll(Arrays.asList(remoteCmd));
        try {
            Process p = new ProcessBuilder(cmd).redirectErrorStream(true).start();
            String out = new String(p.getInputStream().readAllBytes(), "UTF-8");
            boolean finished = p.waitFor(30, TimeUnit.SECONDS);
            if (!finished) { p.destroyForcibly(); return null; }
            return p.exitValue() == 0 ? out : null;
        } catch (IOException | InterruptedException e) {
            return null;
        }
    }
}
